# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_manager_ns: controller_manager
controller_list:
  - name: ar1440/arm_joint_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

ar1440:
  arm_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
  gains:
    joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
