ar1440:
  ar1440_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

    gains:
      joint_1_s: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
      joint_2_l: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
      joint_3_u: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
      joint_4_r: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
      joint_5_b: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
      joint_6_t: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}


  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - finger_joint1
      - finger_joint2
    gains:
      finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      finger_joint2:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

  gazebo_ros_control/pid_gains:
    joint_1_s: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
    joint_2_l: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
    joint_3_u: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
    joint_4_r: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
    joint_5_b: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}
    joint_6_t: {p: 100.0, i: 2.0, d: 2.0, i_clamp: 2.0}

